spring:
  data:
    mongodb:
      uri: mongodb://root:123456@47.97.90.166:27017/test
  redis:
    database: 0 #数据库索引
    host: 47.97.90.166
    port: 6379
    password: 123456
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/h2db
    # schema: classpath:db/schema.sql #，每次启动程序，程序都会运行schema.sql文件，对数据库的数据操作
    # data: classpath:db/data.sql #，每次启动程序，程序都会运行data.sql文件，对数据库的数据操作
    username: root
    password: 123456
    continue-on-error: true
  h2:
    console:
      enabled: true # 开启web console功能
      path: /h2-console # 远程访问地址
      settings:
        web-allow-others: true
mybatis:
  type-aliases-package: cn.bobasyu.entity
